// <auto-generated />
using AccessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessManagement.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AccessManagement.Model.Credentials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("credentials_id");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("principal_id");

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("secret");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("AccessManagement.Model.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("project");
                });

            modelBuilder.Entity("AccessManagement.Model.Credentials", b =>
                {
                    b.HasOne("AccessManagement.Model.Project", null)
                        .WithMany("Credentials")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("AccessManagement.Model.Project", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
